# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('funciones_logros', models.TextField(blank=True, max_length=500)),
                ('meses', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
